### ISSUE TITLE
vite config import throws error

### ISSUE THREAD

**Issue by LucaNerlich** [dansvel/vite-import-markdown#1]
Hey, as soon as I add the plugin to the plugins array, vite breaks:

```bash
failed to load config from C:\Users\[...]\vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\[...]\node_modules\@dansvel\vite-plugin-markdown\index.js
require() of ES modules is not supported.
```

```javascript
import {defineConfig} from 'vite'
import reactRefresh from '@vitejs/plugin-react-refresh'
import vitePluginMarkdown from '@dansvel/vite-plugin-markdown';

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [reactRefresh(), vitePluginMarkdown({sanitize: 'true'}, true)]
})
```

any idea?

Thanks  :)

**Comment by dansvel** [comment]
i still figure it out what it is,, i tried to use it in my sveltest, and works fine, just said

```
marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options
```

i check the link and,, may be it because sanitize is deprecated??

![image](https://user-images.githubusercontent.com/48936611/111893367-d4ea7600-8a34-11eb-907a-df91a004a031.png)

**Comment by LucaNerlich** [comment]
Not sure. I manually copied your files into my project and referenced the plugin from local. It worked then. Something is of with the imports.

**Comment by dansvel** [comment]
yeah, i just update the plugin last couple hours ago,,

okay then, i think we can close this,,?

**Comment by LucaNerlich** [comment]
think so, thanks :)
